id: IF45DA5BF
default_language: en
source: ''
initial_creation_type: tmx
imported: 2022-12-14 10:40:42.020287+00:00
last_modified: 2022-12-14 10:40:42.020291+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: Text
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-11-02T16:08:06.335Z'
  eft-text-id: UT22084-001-001
  eft-text-version: 1.34.6 2020
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_1-1-The_Chapter_on_Going_Forth-v1
bases:
  87DF:
    source_metadata: null
    order: 1
    base_file: 87DF.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
